name: countries
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # Data
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0

  # Bloc
  equatable: ^2.0.7
  flutter_bloc: ^9.1.0

  # Injector
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_lint: ^0.1.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
